# 16

In [1]:
import pandas as pd
from pathlib import Path
import os

current_dir = Path.cwd()
data_path = os.path.join(current_dir, "Industrial_and_Scientific.json")

print("current_dir:", current_dir)
print("data_path:", data_path)

current_dir: /Users/rebecca/Documents/CROUSE/Winter-2025/COMP262-NLP_RS/Project/W25_COMP262_002_TeamGamma
data_path: /Users/rebecca/Documents/CROUSE/Winter-2025/COMP262-NLP_RS/Project/W25_COMP262_002_TeamGamma/Industrial_and_Scientific.json

In [2]:
#load data
dataset = pd.read_json(data_path,orient='records',lines=True)

In [3]:
dataset.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1758333 entries, 0 to 1758332
Data columns (total 12 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   overall         1758333 non-null  int64
 1   verified        1758333 non-null  bool
 2   reviewTime      1758333 non-null  object
 3   reviewerID      1758333 non-null  object
 4   asin            1758333 non-null  object
 5   reviewerName    1758223 non-null  object
 6   reviewText      1757349 non-null  object
 7   summary         1757930 non-null  object
 8   unixReviewTime  1758333 non-null  int64
 9   vote            206308 non-null   object
 10  style           691514 non-null   object
 11  image           32710 non-null    object
dtypes: bool(1), int64(2), object(9)
memory usage: 149.2+ MB

In [4]:
#drop null column of reviewText, summary
dataset = dataset.dropna(subset=['reviewText'])
dataset = dataset.dropna(subset=['summary'])

In [5]:
dataset.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 1757002 entries, 0 to 1758332
Data columns (total 12 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   overall         1757002 non-null  int64
 1   verified        1757002 non-null  bool
 2   reviewTime      1757002 non-null  object
 3   reviewerID      1757002 non-null  object
 4   asin            1757002 non-null  object
 5   reviewerName    1756892 non-null  object
 6   reviewText      1757002 non-null  object
 7   summary         1757002 non-null  object
 8   unixReviewTime  1757002 non-null  int64
 9   vote            206218 non-null   object
 10  style           690977 non-null   object
 11  image           32455 non-null    object
dtypes: bool(1), int64(2), object(9)
memory usage: 162.5+ MB

In [6]:
dataset.head(5)

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,vote,style,image
0,5,True,"01 23, 2013",A3FANY5GOT5X0W,0176496920,Kelly Keyser,"Arrived on time, in mint condition, great! I ...",Just as described!,1358899200,NaN,NaN,NaN
1,5,True,"11 5, 2012",AT6HRPPYOPHMB,0176496920,Michael C,This device was hard to find for my daughter's...,Great device,1352073600,NaN,NaN,NaN
2,4,True,"10 17, 2012",A4IX7B38LIN1E,0176496920,BH,Just a clicker nothing special. Was hoping it ...,Pretty Good,1350432000,NaN,NaN,NaN
3,5,True,"03 29, 2017",A12Q4LR8N17AOZ,0176496920,Waterfall3500,Great response card. Slow shipping but it work...,Thank you for the great product. Works. A++ Us...,1490745600,NaN,NaN,NaN
4,1,True,"03 21, 2017",A1GJXZZPOZ3OD9,0176496920,Amazon Customer,It only lasted for 3 days before it stopped wo...,One Star,1490054400,NaN,NaN,NaN

In [7]:
# Count words in each reviewText
dataset['word_count'] = dataset['reviewText'].apply(lambda x: len(str(x).split()))

long_reviews = dataset[dataset['word_count'] > 100].copy()

In [8]:
import pandas as pd
import difflib
import re

def clean_text(text):
    return re.sub(r"\s+", " ", text.strip().lower())

def is_high_quality_summary(text, summary):
    text = clean_text(text)
    summary = clean_text(summary)
    
    # compare length
    text_len = len(text.split())
    summary_len = len(summary.split())
    compression_ratio = summary_len / max(text_len, 1)
    
    # conparessed
    is_compressed = compression_ratio < 0.35

    # match sequence words 
    matcher = difflib.SequenceMatcher(None, text, summary)
    long_matches = [block for block in matcher.get_matching_blocks() if block.size >= 30]  # 30 letters

    # match ratio
    match_ratio = sum([block.size for block in long_matches]) / max(len(summary), 1)
    is_not_copy = match_ratio < 0.5

    return is_compressed and is_not_copy

# good summary
def evaluate_summaries(df, text_col='reviewText', summary_col='summary'):
    df = df.copy()
    df["is_high_quality"] = df.apply(
        lambda row: is_high_quality_summary(row[text_col], row[summary_col]), axis=1
    )
    return df

In [9]:
df_filtered = evaluate_summaries(long_reviews)

high_quality = df_filtered[df_filtered['is_high_quality']]
low_quality = df_filtered[~df_filtered['is_high_quality']]

print(f"{len(high_quality)} / {len(long_reviews)}")

105941 / 120858

In [10]:
selected_reviews = high_quality.sample(10, random_state=42)

In [11]:
selected_reviews

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,vote,style,image,word_count,is_high_quality
734544,4,True,"01 15, 2014",AEV23XYLMVFZL,B00D7IEAY4,Marcelo Silva,I operate a commercial janitorial services com...,Great value,1389744000,94,NaN,NaN,144,True
789424,5,True,"01 6, 2016",A9AB5APVHTKX8,B00EUKHACW,Canna98,"Having used some of the so called ""Best"" vacuu...",What a Machine!,1452038400,6,{'Size:': ' HV302'},NaN,319,True
991859,5,True,"03 2, 2017",A16ZDXB314DTM6,B00T3ZRI44,Kory,worked for a week and then started making loud...,works only on Smart TV menus,1488412800,NaN,{'Color:': ' Black'},NaN,101,True
245121,5,True,"03 29, 2014",A2805TH6JI69SN,B000W22Z5Y,all the things,This is a great product for the price. I am a ...,Excellent product and company,1396051200,NaN,NaN,NaN,132,True
419395,3,True,"04 2, 2017",ASMTQGULYOY9O,B004AGJ2IG,SonSon,Not bad. I was looking for something to unclog...,Almost a really good product,1491091200,2,{'Package Quantity:': ' 1'},NaN,146,True
14420,3,False,"06 7, 2011",A3KS73J4FNRSJ2,B00005IBW1,Customer,This is a good bet for a generic drugstore whi...,Used this for years with good results,1307404800,4,"{'Size:': ' Kit', 'Style Name:': ' 2-Hour Whit...",NaN,226,True
1199185,5,True,"07 6, 2017",A243TDF8WBG23F,B01FZXLN5C,markmagoo,"If you work in live production, STOP USING DUC...",THE TAPE for live productions (and life),1499299200,NaN,"{'Size:': ' 4 Inch X 30 Yards', 'Color:': ' Bl...",NaN,102,True
1719875,1,True,"06 10, 2016",ABE3ALBA75IUB,B01BLYLUSY,LLShopper,"I've used other brands silica gel before this,...",Doesn't work at all.,1465516800,5,{'Size:': ' 5 lbs'},NaN,148,True
809720,5,True,"03 27, 2015",ADJVGATXSADYT,B00FX36W7O,fishki,I mean that quite literally. Just arrived toda...,This thing sucks.....,1427414400,11,{'Style:': ' Vacuum'},NaN,188,True
798439,5,True,"06 12, 2014",ATHG41G849GIF,B00F9X9WYI,ontopahill,"This thing is an awesome toy and very, very us...","VERY fun toy, but beware of accuracy",1402531200,NaN,{'Size:': ' GXMT38'},NaN,222,True

In [12]:
import os
os.environ["HF_HUB_DISABLE_SYMLINKS_WARNING"] = "1"
os.environ["TRANSFORMERS_NO_TF"] = "1"

In [13]:
# import tensorflow as tf
# tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)

In [14]:
from transformers.pipelines import SUPPORTED_TASKS

print(SUPPORTED_TASKS.keys())

dict_keys(['audio-classification', 'automatic-speech-recognition', 'text-to-audio', 'feature-extraction', 'text-classification', 'token-classification', 'question-answering', 'table-question-answering', 'visual-question-answering', 'document-question-answering', 'fill-mask', 'summarization', 'translation', 'text2text-generation', 'text-generation', 'zero-shot-classification', 'zero-shot-image-classification', 'zero-shot-audio-classification', 'image-classification', 'image-feature-extraction', 'image-segmentation', 'image-to-text', 'image-text-to-text', 'object-detection', 'zero-shot-object-detection', 'depth-estimation', 'video-classification', 'mask-generation', 'image-to-image'])

In [15]:
single_text = selected_reviews.iloc[1]['reviewText']
single_text

'Having used some of the so called "Best" vacuum cleaners ever made etc., I was and am still blown away by this machine!  I had my own cleaning business for 25 plus years and know more than a thing or two about what makes a great vacuum and what is just hype!!  I have seen people buy worthless piles of crap just because it was expensive...therefore it must be good right? NOPE!\nI have been searching for something that was not too expensive, smaller, easy to use and versatile, as I have all hardwood floors and one large area rug with low pile.  Dragging in a canister vac every couple of days really gets old and my OCedar microfiber push broom doesn\'t do the one carpet I have!  I could not bring myself to plop down $300.00 for a Dyson either!  I bought this on Cyber Monday for less than $112.00!\nThere are so many different attachments that come with it, I still have not used them all!  I was astounded at what it pulled out of my area rug, well disgusted is more the word!  The first use was impressive, but every day after that was well ridiculous!  The deep down fine dirt that it pulled out, every day for 2 weeks, blew me away!  Again, I was a professional housekeeper with my own business for 25+ years, I sweep with my OCedar everyday sometimes twice.  Granted, I no longer have small children and a big dog running thru the house everyday, but my family still has no clue what wipe your feet or take them shoes off means!  So being able to switch from the power head to the bare floor attachment as easily as you can and with such a long cord....I love it!  Wish I had bought two!  Or even three!  I know a couple of family members who could use a machine like this!'

In [16]:
from transformers import pipeline

In [17]:
summarizer_gl = pipeline("summarization", model="google-t5/t5-large", framework="pt")

# Apply summarizer to each review
selected_reviews['summary_model'] = selected_reviews['reviewText'].apply(
    lambda x: summarizer_gl(x, max_length=50, min_length=25, do_sample=False)[0]['summary_text']
)

Device set to use mps:0

In [18]:
print("Review1:",selected_reviews.iloc[0]['reviewText'])
print("\nSummary 1:", selected_reviews.iloc[0]['summary_model'])

Review1: I operate a commercial janitorial services company, and for the cost, these are the best backpack vacuums on the market. But it is not perfect.
Cons:
Some of the rivets may break, some sooner than expected (we now have 8 of these, so we bought a cheap rivet tool), and the electrical cables that goes into the vacuum will eventually get loose (they twist off by themselves, if you catch it early, no biggie), and I wish the top would latch on a bit tighter.
Replacement parts are expensive/hard to find
Pros:
Light, powerful and comfortable (this can not be overstated, the back harness is great)
Not a single issue in relation to the motor.
Quiet (in relation).

Are there better vacuums? Yes, but in the $350.00 to $425.00 range. As far as we are concerned, this is far and away the best value.

Summary 1: for the cost, these are the best backpack vacuums on the market, but it is not perfect . some of the rivets may break, some sooner than expected . replacement parts are expensive/hard to find.

In [19]:
print("Review2:",selected_reviews.iloc[1]['reviewText'])
print("\nSummary 2:", selected_reviews.iloc[1]['summary_model'])

Review2: Having used some of the so called "Best" vacuum cleaners ever made etc., I was and am still blown away by this machine!  I had my own cleaning business for 25 plus years and know more than a thing or two about what makes a great vacuum and what is just hype!!  I have seen people buy worthless piles of crap just because it was expensive...therefore it must be good right? NOPE!
I have been searching for something that was not too expensive, smaller, easy to use and versatile, as I have all hardwood floors and one large area rug with low pile.  Dragging in a canister vac every couple of days really gets old and my OCedar microfiber push broom doesn't do the one carpet I have!  I could not bring myself to plop down $300.00 for a Dyson either!  I bought this on Cyber Monday for less than $112.00!
There are so many different attachments that come with it, I still have not used them all!  I was astounded at what it pulled out of my area rug, well disgusted is more the word!  The first use was impressive, but every day after that was well ridiculous!  The deep down fine dirt that it pulled out, every day for 2 weeks, blew me away!  Again, I was a professional housekeeper with my own business for 25+ years, I sweep with my OCedar everyday sometimes twice.  Granted, I no longer have small children and a big dog running thru the house everyday, but my family still has no clue what wipe your feet or take them shoes off means!  So being able to switch from the power head to the bare floor attachment as easily as you can and with such a long cord....I love it!  Wish I had bought two!  Or even three!  I know a couple of family members who could use a machine like this!

Summary 2: i was and am still blown away by this machine! i had my own cleaning business for 25 plus years and know more than a thing or two about what makes a great vacuum and what is just hype . i

## Other test

In [20]:
output_gl = summarizer_gl(single_text, max_length=50, min_length=25, do_sample=False)[0]['summary_text']

print(output_gl)

i was and am still blown away by this machine! i had my own cleaning business for 25 plus years and know more than a thing or two about what makes a great vacuum and what is just hype . i

In [21]:
summarizer_g = pipeline("summarization", model="google/pegasus-xsum", framework="pt")
outputs_g = summarizer_g(single_text, max_length=50, min_length=25, do_sample=False)[0]['summary_text']

print(outputs_g)

Some weights of PegasusForConditionalGeneration were not initialized from the model checkpoint at google/pegasus-xsum and are newly initialized: ['model.decoder.embed_positions.weight', 'model.encoder.embed_positions.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Device set to use mps:0

I have been looking for a vacuum cleaner for a long time and this is the one that I have been looking for!

In [22]:
summarizer_df = pipeline("summarization", model ="google-t5/t5-base", framework="pt")
outputs_df = summarizer_df(single_text, max_length=50,min_length=25, clean_up_tokenization_spaces=True)
print(outputs_df[0]['summary_text'])

Device set to use mps:0

cnn.com's ireport boot camp challenges you to find the best vacuum for your home. the OCedar microfiber push broom vacuum pulls out fine dirt every day for 2 weeks.

In [23]:
prompt = (
    "Summarize this customer review in 2-3 sentences. Highlight the main advantages and disadvantages expressed.Catch the user’s overall sentiment (positive/negative/mixed).Avoid copying the original text directly."
    + single_text
)

summary_df_p = summarizer_df(prompt, max_length=50, min_length=25, do_sample=False)[0]['summary_text']
print(summary_df_p)

i was and am still blown away by this machine! i bought this on cyber monday for less than $112.00!

In [24]:
summarizer_fb = pipeline("summarization", model ="facebook/bart-large-cnn", framework="pt")
outputs_fb = summarizer_fb(single_text, max_length=50,min_length=25, clean_up_tokenization_spaces=True)
print(outputs_fb[0]['summary_text'])

Device set to use mps:0

I was and am still blown away by this machine!  I had my own cleaning business for 25 plus years and know more than a thing or two about what makes a great vacuum. The deep down fine dirt that it pulled out,

In [26]:
pd.set_option('display.max_colwidth', None)

In [27]:
selected_reviews[['reviewText','summary']]

,reviewText,summary
734544,"I operate a commercial janitorial services company, and for the cost, these are the best backpack vacuums on the market. But it is not perfect.\nCons:\nSome of the rivets may break, some sooner than expected (we now have 8 of these, so we bought a cheap rivet tool), and the electrical cables that goes into the vacuum will eventually get loose (they twist off by themselves, if you catch it early, no biggie), and I wish the top would latch on a bit tighter.\nReplacement parts are expensive/hard to find\nPros:\nLight, powerful and comfortable (this can not be overstated, the back harness is great)\nNot a single issue in relation to the motor.\nQuiet (in relation).\n\nAre there better vacuums? Yes, but in the $350.00 to $425.00 range. As far as we are concerned, this is far and away the best value.",Great value
789424,"Having used some of the so called ""Best"" vacuum cleaners ever made etc., I was and am still blown away by this machine! I had my own cleaning business for 25 plus years and know more than a thing or two about what makes a great vacuum and what is just hype!! I have seen people buy worthless piles of crap just because it was expensive...therefore it must be good right? NOPE!\nI have been searching for something that was not too expensive, smaller, easy to use and versatile, as I have all hardwood floors and one large area rug with low pile. Dragging in a canister vac every couple of days really gets old and my OCedar microfiber push broom doesn't do the one carpet I have! I could not bring myself to plop down $300.00 for a Dyson either! I bought this on Cyber Monday for less than $112.00!\nThere are so many different attachments that come with it, I still have not used them all! I was astounded at what it pulled out of my area rug, well disgusted is more the word! The first use was impressive, but every day after that was well ridiculous! The deep down fine dirt that it pulled out, every day for 2 weeks, blew me away! Again, I was a professional housekeeper with my own business for 25+ years, I sweep with my OCedar everyday sometimes twice. Granted, I no longer have small children and a big dog running thru the house everyday, but my family still has no clue what wipe your feet or take them shoes off means! So being able to switch from the power head to the bare floor attachment as easily as you can and with such a long cord....I love it! Wish I had bought two! Or even three! I know a couple of family members who could use a machine like this!",What a Machine!
991859,"worked for a week and then started making loud buzzing sound. works only on Smart TV menus. once video starts playing the buzzing comes back. basically any video play back causes a buzzing\n\nUpdate 3/9/2017\nso the issue was not on the device but tv configuration. I was contact right away after my review. They were pleseant and helpful. I changed the audio format on the tv and boom... Sound from my audio receiver. This device works as avertised. If it does not work for you, check you tv audio settings. I will definitely buy from this company again. Thanks again!!!",works only on Smart TV menus
245121,"This is a great product for the price. I am a nursing student and its much better than the stethoscope that came with my books/tuition fees. It seems very comparable to some of the other students who have the Littmans. Not only is their product great, R.A. Bock the company is fantastic. I ordered a stethoscope from Amazon and upon inspection, noticed there was a small gash in the diaphragm that came on the stethoscope. I sent them an email and they rushed me a brand new stethoscope bubble wrapped for extra protection with a return envelope inside the package to send the defective one back. I would most definitely recommend the product and company. They were very easy to work with and happy to work with me to fix the defect.",Excellent product and company
419395,"Not bad. I was looking for something to unclog the drain pipe going from the dishwasher to the sink drain. Flexible as advertised, the coiled body maneuvered down and through the curved pipe with relative ease. It was almost too bendy as it made pushing with downward force a little tricky. If you don't push straight down, your force would make the brush bend instead of making it go down like you need it to.\n\nThe biggest knock I have is that it was too short. Like, tantalizingly close to being enough to push all the gunk all the way through, but not quite. If you added another inch or two, this drain brush would do the job and get five stars.\n\nSimply put, you make me use my fingers to have to fish out the rest of that disgusting crud, you lose two stars. Yuck.",Almost a really good product
14420,"This is a good bet for a generic drugstore whitener, although I am sure you could do better with higher end kits online. I've used it for a long time and I've experienced good effects, enough for me to keep buying them from time to time when they go on sale or before some big event. I like the fact that it's 2 hour, since you can have faster results.\n\nOne of the reasons I'm docking stars is that this product has gotten more and more ridiculous to use over the years. Initially this product came with two large syringes, whose design allowed you to use every bit of the gel. Now there are a bunch of ridiculous little capsule things, which are nearly impossible to get all the gel out of. It's as if this new design is forcing you to waste product (and allow them to give you less). Just leaves kind of a bad feeling that a company would purposely make something worse like that.\n\nI think I stick with it more that I've had history with it than anything else, since I've never had any sensitivity or irritation. Next time I will buy a higher strength whitening kit online. But if you're at a drugstore and that's the only thing you have with 2 hours before a nice event, go for it.",Used this for years with good results
1199185,"If you work in live production, STOP USING DUCT TAPE.\nIf you love your equipment, floors, and wired, you need Gaf Tape. I've worked with a bunch of Gaf Tape in my lifetime and figured they were all the same. Then someone bought me a roll after using one of mine up. Not all Gaf Tape is made equal, and this stuff is proof. Or maybe that crap gaf was proof. Either way, this is all I get now. Plus, wider tape is never a bad thing to have on hand. Gaf Tape will change your life. I recommend REAL Gaf Tape.",THE TAPE for live productions (and life)
1719875,"I've used other brands silica gel before this, and all have worked fairly well. I decided to try this brand after having trouble baking the moisture out of the other brands (baked for 5 hours -- didn't do much 'cept waste gas) Now, one good test of a product such as this is to take a tablespoon of it and put it, along with a tablespoon of water into a plastic cup. The gel should absorb the water completely, leaving only wet globules. After replacing the old silica gel in my safe with this product, I noticed (after a few days) that the hygrometer in my safe was reading kind of high, so I did the above test with this product. Result? Didn't absorb a darn'd thing. Just gave off a crackling sound, like Rice Krispies, but much louder. In any case, this stuff is less than worthless.",Doesn't work at all.
809720,"I mean that quite literally. Just arrived today and after I put it together I thought I would try it out. WOW! sucked up all the packaging that everything came in, didn't mean to, was just going after a leaf on the carpet, scared the hell out of the cat cause she was playing with the plastic wrappers. Good thing she wasn't closer or I might be needing a new pet.\n\nI can say this seems to be more powerful than the Shop Vac I own that is the same size. Plus I like the caddy bag that is on the handle to keep all the attachments in. We will see how this holds up on a couple jobsites.\n\nUpdate : 4/5/2017, Ok so its been a couple years, this thing is still going strong, still has the suction power as it did when new. Everything from sawdust, to plaster chunks, nails, screws you name it, I have sucked it up. I even used it to retrieve a screwdriver that was dropped down inside a 4"" cast iron vent pipe while I was taking out some old plumbing.",This thing sucks.....
798439,"This thing is an awesome toy and very, very useful and if used correctly, will pay for itself many, many times over. Think about it, how many times have you wanted to check the temperature for a particular spot? I've used it (and will use it) for checking the temperature at various parts of the room (and various rooms), checking the temp from air coming out of the vent, checking for leaks around windows, checking grill temperature, checking fridge/freezer temps, checking coffee temperature, etc. The list goes on and on. I brought it to work and all of my co-workers want to borrow it to use it around their homes.\n\nBe advised, though, that this isn't going to replace a reliable ear thermometer to check your temp. You should have the expectation of it being off by a couple degrees and it definitely shows about 2 degrees higher than all of the digital thermostats are showing. If you need more accuracy, this device may not be for you. Its more about finding problems with big temperature differences, NOT for precise measurements.\n\nGet it. I haven't owned it long (I'm sure I'll update it if it fails) so I don't know long term reliability, but I wouldn't expect much to fail, so it should be a great useful product for years to come.","VERY fun toy, but beware of accuracy"

In [28]:
review = selected_reviews.iloc[0]['reviewText']

# 17

In [29]:
import pandas as pd
import re

question_words = ["what", "why", "how", "can", "could", "would", "do", "does", "did", "is", "are", "was", "were", "should", "may"]

def is_question_review(text):
    if "?" in text:
        return True
    return any(re.match(rf"^\s*{q}\b", text.strip().lower()) for q in question_words)

high_quality["is_question_like"] = high_quality["reviewText"].apply(is_question_review)

question_review = high_quality[high_quality["is_question_like"]].sample(10, random_state=42)

/var/folders/60/83kzkx2x4hs5zc8lx2tyc8lw0000gn/T/ipykernel_37836/81743553.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  high_quality["is_question_like"] = high_quality["reviewText"].apply(is_question_review)

In [30]:
question_review["reviewText"]

694454                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Stop crying people, the item description says that it reads in Celsius.  Why in the world would you buy a product that's description says it reads only in Celsius, then rate it low and complain that it doesn't work for Fahrenheit?  If you can't convert with the app for smartphones and learn to work with Celsius, then don't buy this item.  Go find the Fahrenheit version and pay a few bucks extra for it, don't buy the Celsius version and whine.\n\nThat said, it works just great.  I need to keep my tanks heated to about 72F, so I set the unit for 22C and off we go.  It comes on when I have it set for and shuts down when it hits temp.  It works just great, running two heating elements off the heating relay.  I don't have anything hooked up to the cooling side since I don't need that side of it.  For the price you can't beat this anywhere even if you only need one side of it, and considering that it runs two relays, one for heating and one for cooling, it's amazing at this price.  Well worth learning to use an app on my phone or  making up a chart for temps you need converted.\n\nI wish I could rate it about 20 stars to make up for the people that rate it low because it does what the item description says it does, Celsius only.  Why anyone would buy and item that says in it's description that it only reads Celsius and then complain that it won't switch to Fahrenheit I can't figure out, especially when there is a version of this item that reads F and cost just a few bucks more.

In [31]:
text_question = high_quality["reviewText"][270552]
text_question

"I buy a lot of stuffs from Amazon and this would be my very first review.  As a contractor, I have other higher end backpack vacuum.  I was hoping to buy this smaller version to use around the house for simple use on all my hardwood floor.  First impression when I opened the box was - this is all cheap materials.  I thought to myself, I got what I paid for.  But I decided to give it a try anyway.  The vacuum was so weak that it barely can pick up all the trash/dust.  Could there be something defective on my unit?  Doesn't seem like it.  Motor and everything was running fine.  I am returning this vacuum and would not recommend this to anyone.  I don't know how it got over 4+ stars from nearly 30 people.  I usually can rely on Amazon reviews but not on this vacuum.  What a disappointment and big waste of time."

In [32]:
text_question_2 = high_quality["reviewText"][1123475]
text_question_2

'First time I\'ve tired these and the cloth is stuck in the line. Does anyone know how to best unclog the "cleaning" cloth from the line?\n\nEdit: I googled my issue and ended up hooking my regular vacuum up to the central vac outlet to try sucking the cloth back out. The cloth didn\'t come back up, but some other gunk did. I then plugged the central vac hose back in and heard material unclog and end up in the central vac unit. It looks like it was so clogged that the cloth could\'t pass though until I suctioned it the other direction to get it all moving. Now it is working well and I will give the cloths another try.'

In [33]:
from transformers import pipeline

qa_pipeline = pipeline("question-answering", model="distilbert-base-uncased-distilled-squad", framework="pt")

Device set to use mps:0

In [34]:
question = "How can I unclog the cleaning cloth from the line?"

context = text_question_2

response = qa_pipeline(question=question, context=context)

print("Question:", question)
print("Answer:", response['answer'])

Question: How can I unclog the cleaning cloth from the line?
Answer: plugged the central vac hose

In [35]:
question = "Could there be something defective on my unit?"

context = text_question

response = qa_pipeline(question=question, context=context)

print("Question:", question)
print("Answer:", response['answer'])

Question: Could there be something defective on my unit?
Answer: Could there be something defective on my unit?  Doesn't seem like it

In [36]:
question = "Is this a good vacuum cleaner?"

context = text_question

response = qa_pipeline(question=question, context=context)

print("Question:", question)
print("Answer:", response['answer'])

Question: Is this a good vacuum cleaner?
Answer: I usually can rely on Amazon reviews but not on this vacuum